### ISSUE TITLE
support for posting images

### ISSUE THREAD

**Issue by glyph** [tr3buchet/gister#16]
apparently it's possible to put images into a gist? http://stackoverflow.com/questions/16425770/how-do-you-upload-images-to-a-gist has some more details. it would be cool to be able to use this.  right now I just get a UTF-8 decode error when I try.

**Comment by tr3buchet** [comment]
I am looking into this. So far it does not look good though. Anything I send that is base64 encoded just ends up as a text file named whatever.png as seen [here](https://gist.github.com/tr3buchet/0abc9e23a9bfe05dfb59). I don't want gister to make git calls because it assumes you configured git and I use gister all the time on machines that I can't or don't want to configure git.

**Comment by glyph** [comment]
Does the new file-upload stuff they've been advertising in the UI all over the place impact this at all?  Is there a new API for that, maybe?

**Comment by tr3buchet** [comment]
Looks like it doesn't and there isn't. I reached out to Github support and they replied "the Gist API doesn't support uploading binary files at the moment, so if you need to add an image to a gist for example, you'd need to clone it locally and push the image."

With that response I'm going to close this issue for now as it is beyond the scope of gister to integrate git while making all sorts of assumptions about it being installed and configured.

Gisting of images is super cool though and should they add binary file gists to the API in the future, I'll gladly implement support for it in gister cause we use it all the time.
